
name: TestPerformance

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

permissions:
  contents: write

jobs:
  TestPackage:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.13"]
        os: ["ubuntu-latest"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    - name: Test Performance with unittest
      run: |
        cp ./Test/testresults_template.csv ./Test/testresults.csv
        python -m build
        pip install --find-links=./dist cloudcrypt
        python -m unittest discover -s Test -p performance_test_*.py
    - uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: Added Performance Test results
        file_pattern: '*results.csv'
